//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Resources/Action Assets/Keybinds.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Keybinds: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Keybinds()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Keybinds"",
    ""maps"": [
        {
            ""name"": ""UserControls"",
            ""id"": ""7008b348-9410-4d3f-abc4-8733345db1ad"",
            ""actions"": [
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""f6c4190c-2a74-474d-8955-56e1c393fdcf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""940bc970-c9db-4fa8-b002-fd9ce65b513d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""78d21d3c-5306-4a0d-80c3-2b53b73bb7b7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""bc1c7006-aef3-406a-96cc-8f3aec8ffce5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""2a50f9ba-c98a-4011-869f-a1ecfb4a15bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Parry"",
                    ""type"": ""Button"",
                    ""id"": ""5beea02f-826e-4c1c-be9d-94d60f91b43d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomOut"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fb014be8-83a9-49b5-b967-ef9df69512d4"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomIn"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7e937cc7-d9dd-4f85-913d-6ad8511db8eb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""85844801-933b-423d-a5b1-1a916f540ae0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""ce409df8-d32e-4357-9dfe-16f92bc8bbea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug"",
                    ""type"": ""Button"",
                    ""id"": ""b3178e13-4cd0-4b24-83bb-9e568b8647bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""89e510a5-1f9c-46cf-9d25-54bbe3a50fde"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e2f2f165-13e6-4afe-8f98-a27184ae782b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c0729b6-ea7d-4f08-8258-e2d317c95a76"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b168123-8495-49db-86dc-a9857d498be3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c95433c3-4ccf-4f17-9515-a06fd51875bd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8513117-2874-4ee3-afd3-13daf42381ec"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abc83662-e8df-42ef-9bf2-aebacc81ab70"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ad431dc-2693-4bd0-993b-75c3de1e357c"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""453986bf-9194-493c-86a6-7274b8b09aa9"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6fa129ee-8fe2-473c-b538-6347e31c5757"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79019dc6-5854-477a-abfd-c52b94493fea"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c03dabc-0382-495b-9a8d-d5618ab1a8a3"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adfc608d-a0c1-4e15-9594-15838e96c633"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DefaultControls"",
            ""id"": ""e008db53-c5cf-4003-ae65-b51106790581"",
            ""actions"": [
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""f1270007-52f6-41c1-a2f9-d5c178f0ac40"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6c23898e-aa0b-4864-9814-09a9b73ed4e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""db33ebf7-617f-47fc-ab98-1b050b931881"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""393cc77f-8e9f-405b-a707-16f598f4d44d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""2e2779ca-6a78-4d6c-bcb6-5790e775f0c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Parry"",
                    ""type"": ""Button"",
                    ""id"": ""ce07408d-740f-4adc-92fe-7e798077a77f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomOut"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f68de6a8-2fa5-4389-b22a-ddd0b9e76f81"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomIn"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4f58498f-6418-434f-8cd6-db837bb72a54"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""59a6f256-87f2-449f-9035-9e5e25887465"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""505011f4-1ccf-4562-a92f-06b12fc51e85"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug"",
                    ""type"": ""Button"",
                    ""id"": ""a050f97e-72de-492e-8c8c-edbca54acf73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""5cc786f3-0cf5-4587-97c0-91129c66719a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4a608276-43b1-4999-a5cf-21e5a76c3614"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a168537a-05d0-4ff6-9519-81b7a7355e6b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39744989-4bc9-4beb-af41-fa19428fc34e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b06f2c7c-e45d-4c10-8682-50ecb8ff780c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94b78990-ac6a-4b47-b09b-055fc94a7eac"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2033e9cf-64e2-4144-93f3-1adebe95a093"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Parry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfa1a53c-26a9-4461-a6eb-8a19fd895682"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f478ec09-3b69-472d-b21f-dd85e189899d"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1254d7e-e9f2-4046-96d1-7818971991dc"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e63eb611-40cc-4649-9ecc-3490dec09d0e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ba67890-131b-4791-8d2e-4520cd9912f3"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51720879-186b-4abb-8382-c80e4a913a0f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RebindControls"",
            ""id"": ""1a1797e4-7361-4902-80d3-32c3a880960e"",
            ""actions"": [
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""5eec5c94-8a34-4753-8689-ae7c0eef4499"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f669589d-7180-4717-b25c-e871eeefc86e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UserControls
        m_UserControls = asset.FindActionMap("UserControls", throwIfNotFound: true);
        m_UserControls_Right = m_UserControls.FindAction("Right", throwIfNotFound: true);
        m_UserControls_Jump = m_UserControls.FindAction("Jump", throwIfNotFound: true);
        m_UserControls_Left = m_UserControls.FindAction("Left", throwIfNotFound: true);
        m_UserControls_Interact = m_UserControls.FindAction("Interact", throwIfNotFound: true);
        m_UserControls_Attack = m_UserControls.FindAction("Attack", throwIfNotFound: true);
        m_UserControls_Parry = m_UserControls.FindAction("Parry", throwIfNotFound: true);
        m_UserControls_ZoomOut = m_UserControls.FindAction("ZoomOut", throwIfNotFound: true);
        m_UserControls_ZoomIn = m_UserControls.FindAction("ZoomIn", throwIfNotFound: true);
        m_UserControls_Dash = m_UserControls.FindAction("Dash", throwIfNotFound: true);
        m_UserControls_Exit = m_UserControls.FindAction("Exit", throwIfNotFound: true);
        m_UserControls_Debug = m_UserControls.FindAction("Debug", throwIfNotFound: true);
        m_UserControls_Up = m_UserControls.FindAction("Up", throwIfNotFound: true);
        // DefaultControls
        m_DefaultControls = asset.FindActionMap("DefaultControls", throwIfNotFound: true);
        m_DefaultControls_Right = m_DefaultControls.FindAction("Right", throwIfNotFound: true);
        m_DefaultControls_Jump = m_DefaultControls.FindAction("Jump", throwIfNotFound: true);
        m_DefaultControls_Left = m_DefaultControls.FindAction("Left", throwIfNotFound: true);
        m_DefaultControls_Interact = m_DefaultControls.FindAction("Interact", throwIfNotFound: true);
        m_DefaultControls_Attack = m_DefaultControls.FindAction("Attack", throwIfNotFound: true);
        m_DefaultControls_Parry = m_DefaultControls.FindAction("Parry", throwIfNotFound: true);
        m_DefaultControls_ZoomOut = m_DefaultControls.FindAction("ZoomOut", throwIfNotFound: true);
        m_DefaultControls_ZoomIn = m_DefaultControls.FindAction("ZoomIn", throwIfNotFound: true);
        m_DefaultControls_Dash = m_DefaultControls.FindAction("Dash", throwIfNotFound: true);
        m_DefaultControls_Exit = m_DefaultControls.FindAction("Exit", throwIfNotFound: true);
        m_DefaultControls_Debug = m_DefaultControls.FindAction("Debug", throwIfNotFound: true);
        m_DefaultControls_Up = m_DefaultControls.FindAction("Up", throwIfNotFound: true);
        // RebindControls
        m_RebindControls = asset.FindActionMap("RebindControls", throwIfNotFound: true);
        m_RebindControls_Cancel = m_RebindControls.FindAction("Cancel", throwIfNotFound: true);
    }

    ~@Keybinds()
    {
        UnityEngine.Debug.Assert(!m_UserControls.enabled, "This will cause a leak and performance issues, Keybinds.UserControls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_DefaultControls.enabled, "This will cause a leak and performance issues, Keybinds.DefaultControls.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_RebindControls.enabled, "This will cause a leak and performance issues, Keybinds.RebindControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UserControls
    private readonly InputActionMap m_UserControls;
    private List<IUserControlsActions> m_UserControlsActionsCallbackInterfaces = new List<IUserControlsActions>();
    private readonly InputAction m_UserControls_Right;
    private readonly InputAction m_UserControls_Jump;
    private readonly InputAction m_UserControls_Left;
    private readonly InputAction m_UserControls_Interact;
    private readonly InputAction m_UserControls_Attack;
    private readonly InputAction m_UserControls_Parry;
    private readonly InputAction m_UserControls_ZoomOut;
    private readonly InputAction m_UserControls_ZoomIn;
    private readonly InputAction m_UserControls_Dash;
    private readonly InputAction m_UserControls_Exit;
    private readonly InputAction m_UserControls_Debug;
    private readonly InputAction m_UserControls_Up;
    public struct UserControlsActions
    {
        private @Keybinds m_Wrapper;
        public UserControlsActions(@Keybinds wrapper) { m_Wrapper = wrapper; }
        public InputAction @Right => m_Wrapper.m_UserControls_Right;
        public InputAction @Jump => m_Wrapper.m_UserControls_Jump;
        public InputAction @Left => m_Wrapper.m_UserControls_Left;
        public InputAction @Interact => m_Wrapper.m_UserControls_Interact;
        public InputAction @Attack => m_Wrapper.m_UserControls_Attack;
        public InputAction @Parry => m_Wrapper.m_UserControls_Parry;
        public InputAction @ZoomOut => m_Wrapper.m_UserControls_ZoomOut;
        public InputAction @ZoomIn => m_Wrapper.m_UserControls_ZoomIn;
        public InputAction @Dash => m_Wrapper.m_UserControls_Dash;
        public InputAction @Exit => m_Wrapper.m_UserControls_Exit;
        public InputAction @Debug => m_Wrapper.m_UserControls_Debug;
        public InputAction @Up => m_Wrapper.m_UserControls_Up;
        public InputActionMap Get() { return m_Wrapper.m_UserControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UserControlsActions set) { return set.Get(); }
        public void AddCallbacks(IUserControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_UserControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UserControlsActionsCallbackInterfaces.Add(instance);
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Parry.started += instance.OnParry;
            @Parry.performed += instance.OnParry;
            @Parry.canceled += instance.OnParry;
            @ZoomOut.started += instance.OnZoomOut;
            @ZoomOut.performed += instance.OnZoomOut;
            @ZoomOut.canceled += instance.OnZoomOut;
            @ZoomIn.started += instance.OnZoomIn;
            @ZoomIn.performed += instance.OnZoomIn;
            @ZoomIn.canceled += instance.OnZoomIn;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
            @Debug.started += instance.OnDebug;
            @Debug.performed += instance.OnDebug;
            @Debug.canceled += instance.OnDebug;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
        }

        private void UnregisterCallbacks(IUserControlsActions instance)
        {
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Parry.started -= instance.OnParry;
            @Parry.performed -= instance.OnParry;
            @Parry.canceled -= instance.OnParry;
            @ZoomOut.started -= instance.OnZoomOut;
            @ZoomOut.performed -= instance.OnZoomOut;
            @ZoomOut.canceled -= instance.OnZoomOut;
            @ZoomIn.started -= instance.OnZoomIn;
            @ZoomIn.performed -= instance.OnZoomIn;
            @ZoomIn.canceled -= instance.OnZoomIn;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
            @Debug.started -= instance.OnDebug;
            @Debug.performed -= instance.OnDebug;
            @Debug.canceled -= instance.OnDebug;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
        }

        public void RemoveCallbacks(IUserControlsActions instance)
        {
            if (m_Wrapper.m_UserControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUserControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_UserControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UserControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UserControlsActions @UserControls => new UserControlsActions(this);

    // DefaultControls
    private readonly InputActionMap m_DefaultControls;
    private List<IDefaultControlsActions> m_DefaultControlsActionsCallbackInterfaces = new List<IDefaultControlsActions>();
    private readonly InputAction m_DefaultControls_Right;
    private readonly InputAction m_DefaultControls_Jump;
    private readonly InputAction m_DefaultControls_Left;
    private readonly InputAction m_DefaultControls_Interact;
    private readonly InputAction m_DefaultControls_Attack;
    private readonly InputAction m_DefaultControls_Parry;
    private readonly InputAction m_DefaultControls_ZoomOut;
    private readonly InputAction m_DefaultControls_ZoomIn;
    private readonly InputAction m_DefaultControls_Dash;
    private readonly InputAction m_DefaultControls_Exit;
    private readonly InputAction m_DefaultControls_Debug;
    private readonly InputAction m_DefaultControls_Up;
    public struct DefaultControlsActions
    {
        private @Keybinds m_Wrapper;
        public DefaultControlsActions(@Keybinds wrapper) { m_Wrapper = wrapper; }
        public InputAction @Right => m_Wrapper.m_DefaultControls_Right;
        public InputAction @Jump => m_Wrapper.m_DefaultControls_Jump;
        public InputAction @Left => m_Wrapper.m_DefaultControls_Left;
        public InputAction @Interact => m_Wrapper.m_DefaultControls_Interact;
        public InputAction @Attack => m_Wrapper.m_DefaultControls_Attack;
        public InputAction @Parry => m_Wrapper.m_DefaultControls_Parry;
        public InputAction @ZoomOut => m_Wrapper.m_DefaultControls_ZoomOut;
        public InputAction @ZoomIn => m_Wrapper.m_DefaultControls_ZoomIn;
        public InputAction @Dash => m_Wrapper.m_DefaultControls_Dash;
        public InputAction @Exit => m_Wrapper.m_DefaultControls_Exit;
        public InputAction @Debug => m_Wrapper.m_DefaultControls_Debug;
        public InputAction @Up => m_Wrapper.m_DefaultControls_Up;
        public InputActionMap Get() { return m_Wrapper.m_DefaultControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultControlsActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultControlsActionsCallbackInterfaces.Add(instance);
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Parry.started += instance.OnParry;
            @Parry.performed += instance.OnParry;
            @Parry.canceled += instance.OnParry;
            @ZoomOut.started += instance.OnZoomOut;
            @ZoomOut.performed += instance.OnZoomOut;
            @ZoomOut.canceled += instance.OnZoomOut;
            @ZoomIn.started += instance.OnZoomIn;
            @ZoomIn.performed += instance.OnZoomIn;
            @ZoomIn.canceled += instance.OnZoomIn;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
            @Debug.started += instance.OnDebug;
            @Debug.performed += instance.OnDebug;
            @Debug.canceled += instance.OnDebug;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
        }

        private void UnregisterCallbacks(IDefaultControlsActions instance)
        {
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Parry.started -= instance.OnParry;
            @Parry.performed -= instance.OnParry;
            @Parry.canceled -= instance.OnParry;
            @ZoomOut.started -= instance.OnZoomOut;
            @ZoomOut.performed -= instance.OnZoomOut;
            @ZoomOut.canceled -= instance.OnZoomOut;
            @ZoomIn.started -= instance.OnZoomIn;
            @ZoomIn.performed -= instance.OnZoomIn;
            @ZoomIn.canceled -= instance.OnZoomIn;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
            @Debug.started -= instance.OnDebug;
            @Debug.performed -= instance.OnDebug;
            @Debug.canceled -= instance.OnDebug;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
        }

        public void RemoveCallbacks(IDefaultControlsActions instance)
        {
            if (m_Wrapper.m_DefaultControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultControlsActions @DefaultControls => new DefaultControlsActions(this);

    // RebindControls
    private readonly InputActionMap m_RebindControls;
    private List<IRebindControlsActions> m_RebindControlsActionsCallbackInterfaces = new List<IRebindControlsActions>();
    private readonly InputAction m_RebindControls_Cancel;
    public struct RebindControlsActions
    {
        private @Keybinds m_Wrapper;
        public RebindControlsActions(@Keybinds wrapper) { m_Wrapper = wrapper; }
        public InputAction @Cancel => m_Wrapper.m_RebindControls_Cancel;
        public InputActionMap Get() { return m_Wrapper.m_RebindControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RebindControlsActions set) { return set.Get(); }
        public void AddCallbacks(IRebindControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_RebindControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RebindControlsActionsCallbackInterfaces.Add(instance);
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
        }

        private void UnregisterCallbacks(IRebindControlsActions instance)
        {
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
        }

        public void RemoveCallbacks(IRebindControlsActions instance)
        {
            if (m_Wrapper.m_RebindControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRebindControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_RebindControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RebindControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RebindControlsActions @RebindControls => new RebindControlsActions(this);
    public interface IUserControlsActions
    {
        void OnRight(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnParry(InputAction.CallbackContext context);
        void OnZoomOut(InputAction.CallbackContext context);
        void OnZoomIn(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
        void OnDebug(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
    }
    public interface IDefaultControlsActions
    {
        void OnRight(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnParry(InputAction.CallbackContext context);
        void OnZoomOut(InputAction.CallbackContext context);
        void OnZoomIn(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
        void OnDebug(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
    }
    public interface IRebindControlsActions
    {
        void OnCancel(InputAction.CallbackContext context);
    }
}
